### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by nssidhu** [egvijayanand/dotnet-maui-samples#11]
Tried using your TestApp Project in visual Studio 2022 Version 17.1.0 Preview 4.0

Too many compile Error

![image](https://user-images.githubusercontent.com/3267605/151671203-45759b93-d8dd-4c1f-8b12-e507729d3072.png)

**Comment by egvijayanand** [comment]
Hi,

It’s been quite a while that repo is updated with. Busy with other commitments.

Have planned to update it tomorrow, you’ll receive notification as part of this issue update.

You can pull the changes post that.

Regards,
Vijay Anand E G
________________________________
From: ns ***@***.***>
Sent: Saturday, January 29, 2022 11:06:12 PM
To: egvijayanand/dotnet-maui-samples ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [egvijayanand/dotnet-maui-samples] Fails to build (Issue #11)


Tried using your TestApp Project in visual Studio 2022 Version 17.1.0 Preview 4.0

Too many compile Error

[image]<https://user-images.githubusercontent.com/3267605/151671203-45759b93-d8dd-4c1f-8b12-e507729d3072.png>

**Comment by egvijayanand** [comment]
Hi @nssidhu,

The source has been updated to clear the errors when built on top of the latest preview (VS2022 17.1.0 Preview 4.0).

Request to pull the latest changes and then try building it in your machine.

Will add a reminder to update this repo whenever a new preview is released.

Regards,
Vijay Anand E G

**Comment by nssidhu** [comment]
Still running into compile issues

![image](https://user-images.githubusercontent.com/3267605/151727760-d68e604a-06d1-455c-9fd3-fa174dfba9d1.png)

**Comment by egvijayanand** [comment]
Hi,

Can you remove the hyphen in font file ‘OpenSans-Regular.ttf’ (Resources\Fonts folder) and update the same in MauiProgram.cs as well.

The other errors will go away automatically once this is done.

Regards,
Vijay Anand E G
________________________________

**Comment by egvijayanand** [comment]
Hi @nssidhu,

Sorry for the inconvenience.

Have verified with Windows as the target framework, pushed the changes to the repo as it worked as expected.

Should have made sure whether the other target frameworks were building properly or not. Assuring it won't happen in the future.

Thanks for your patience.

Regards,
Vijay Anand E G
