### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by plettb** [egvijayanand/dotnet-maui-samples#16]
This is relatively trivial, but with a new, clean copy of the source, when I try to run on a Windows machine, it builds fine but produces the following problem when attempting to run (deploy):

Severity	Code	Description	Project	File	Line	Suppression State
Error		DEP0700: Registration of the app failed. [0x80073CF6] AppxManifest.xml(33,27): error 0x80070003: Cannot install or update package ddf6acdf-63c8-4550-a5ad-d225a2822643_9zz4h110yvjzm because the splash screen image [appiconfgSplashScreen.png] cannot be located. Verify that the package contains an image that can be used as a splash screen for the application, and that the package manifest points to the correct location in the package where this splash screen image can be found.	TestApp			

It's simple enough to get past this error simply by deleting the splash screen reference in "Platforms\Windows\Package.appxmanifest", but I thought you might want to fix it for real. :)

**Comment by egvijayanand** [comment]
Hi @plettb,

Since the source is not yet updated to reflect the Preview 13 changes, it's cribbing.

There's a slight change in this Preview about how images are handled in the Windows target platform.

Will make the necessary changes and push a new update.

Regards,
Vijay Anand E G

**Comment by egvijayanand** [comment]
Hi @plettb,

Samples have been updated to incorporate the changes of Preview 13.

Kindly update.

Regards,
Vijay Anand E G

**Comment by plettb** [comment]
Thanks a lot!  Works like a charm. :)
