### ISSUE TITLE
Forced Login?

### ISSUE THREAD

**Issue by plettb** [egvijayanand/dotnet-maui-samples#18]
This is not an issue, really.  It is a question, and maybe an enhancement request.  I'm quite new to Maui development, especially the navigation.  In the app I'm currently writing I need to force login.  In other words, no pages are available if the user is not logged in, and if the user logs out, he/she is taken back to the login page.  Can you give me an idea how to accomplish this?  This app looks like it's quite close, but I can't seem to figure out how to make it do what I'm trying.

Thanks a lot!

**Comment by egvijayanand** [comment]
Hi @plettb,

Glad to know you're trying out .NET MAUI.

Update the App.xaml.cs to the below snippet to ensure the pages are accessible only if the user is logged in.

```csharp
namespace TestApp
{
    public partial class App : Application
    {
        public App()
        {
            InitializeComponent();

            MainPage = new AppShell();

            // Add logic to check whether the user is authenticated or not and then update the Authenticated flag
            // Could be like verifying whether a user access token is available in the secure storage ...
            // If not available, redirect the user to the Login page

            if (!Authenticated)
            {
                Shell.Current.GoToAsync("//login");
            }
        }

        public bool Authenticated { get; internal set; }
    }
}
```

The logic can be further updated to auto-redirect to the Login page whenever the Authenticated flag turns to false.

Regards,
Vijay Anand E G
